#!/usr/bin/bash

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

if [[ "$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)" == *"[MUTED]"* ]]; then
    notify-send "  Microphone muted"
else
    notify-send " Microphone unmuted"
fi
